### ISSUE TITLE
Doesn't work on Gnome 3.36

### ISSUE THREAD

**Issue by inducer** [timbertson/slinger#27]
Here we are again. :) I haven't had time to investigate yet.

**Comment by inducer** [comment]
I guess I should describe what's wrong: None of the keyboard shortcuts appear to do anything.

**Comment by inducer** [comment]
I lied. Most things work, just the Super+A menu seems broken, with
```
Apr 19 20:22:34 lightning gnome-shell[2313]: [slinger]:Error: TypeError: Sys.Clutter.DeviceManager is undefined
```

**Comment by inducer** [comment]
Scanning through how the "stock" Gnome extensions do grabs, I stumbled upon `Main.pushModal`. Example usage [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/blob/f4013c7a5c572919c12274f23b8eeab9be18efb2/extensions/window-list/windowPicker.js#L229). Maybe that's a better way?

**Comment by timbertson** [comment]
Given 4f9bbe7e75eb90c51d752503105d37894c075dc6 I'd love to stop talking to `DeviceManager`. Looks like this code was only added in 0d957abbc63f5901355b7aad0a64606496cc543c because `Sys.Clutter.grab_pointer` and `grab_keyboard` disappeared in 3.34, so "here we go again" is exactly right :/

If you can have a try and see if `pushhModal` works, that'd be great. I don't think I'll have time to try out 3.36 anytime soon.

**Comment by timbertson** [comment]
Thanks for the push/pop modal pointer. It didn't fully work (still need to take a keyboard grab), but seems to be necessary all the same. The missing DeviceManager became a clutter "seat".

Also it _seems_ like https://gitlab.gnome.org/GNOME/mutter/issues/799 is no longer an issue?. It's working for me after hotplug now without the hack. You too?

**Comment by inducer** [comment]
:tada: Thanks! I can confirm that nothing seems broken upon pulling your changes. I'll only find out about hotplug over the next couple days. If you don't hear from me, you can assume that it's fine. :P
